<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1080, height=1920" />
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <style>
      /*
       * History Unlocked — daily short, 25 September: Stamford Bridge, 1066.
       * TEMPLATE — index.html is generated by tools/build-composition.mjs from
       * this file, script.json and the measured narration. Edit this, not
       * index.html. Same design as day-1869-black-friday.
       *
       * TikTok safe zone: top ~150px, bottom ~400px, right ~130px stay clear.
       */
      @font-face { font-family: "Anton"; src: url("fonts/anton-normal.woff2") format("woff2"); font-weight: 400; font-style: normal; }
      @font-face { font-family: "DM Serif Display"; src: url("fonts/dmserif-normal.woff2") format("woff2"); font-weight: 400; font-style: normal; }
      @font-face { font-family: "DM Serif Display"; src: url("fonts/dmserif-italic.woff2") format("woff2"); font-weight: 400; font-style: italic; }

      :root {
        --void: #06070a;
        --ink-raised: #141826;
        --gold: #f5b73b;
        --gold-soft: rgba(245, 183, 59, 0.22);
        --text: #f4f6fb;
        --text-2: rgba(244, 246, 251, 0.78);
        --crash: #ff5470;
      }
      * { margin: 0; padding: 0; box-sizing: border-box; }
      html, body { margin: 0; overflow: hidden; background: var(--void); }
      #root { position: relative; width: 100%; height: 100%; overflow: hidden; background: var(--void); color: var(--text); }

      .scene { position: absolute; inset: 0; overflow: hidden; }
      .layer { position: absolute; inset: 0; }
      .solid { background: var(--void); }
      .cover { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; display: block; }
      .shade {
        background:
          radial-gradient(ellipse 90% 60% at 50% 38%, rgba(6, 7, 10, 0.35), rgba(6, 7, 10, 0.86) 70%),
          rgba(6, 7, 10, 0.25);
      }
      .glow { background: radial-gradient(ellipse 70% 45% at 50% 40%, var(--gold-soft), transparent 70%); }
      .content {
        position: absolute; inset: 0; display: flex; flex-direction: column;
        padding: 200px 150px 420px 72px; gap: 18px; box-sizing: border-box;
      }
      .kicker {
        font-family: "Anton", sans-serif; font-size: 46px; letter-spacing: 0.2em;
        color: var(--gold); text-transform: uppercase; line-height: 1.05;
      }
      .label {
        font-family: "Anton", sans-serif; font-size: 40px; letter-spacing: 0.08em;
        text-transform: uppercase; color: var(--text); line-height: 1.1;
      }
      .serif { font-family: "DM Serif Display", serif; font-weight: 400; text-wrap: balance; }
      .italic { font-family: "DM Serif Display", serif; font-style: italic; text-wrap: balance; }
      .rule { width: 100%; max-width: 560px; height: 4px; background: var(--gold); }
      .frame { position: relative; width: 100%; overflow: hidden; border: 3px solid var(--gold); background: var(--ink-raised); }
      .frame img { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; display: block; }
      .ghost {
        position: absolute; left: -40px; top: 250px; font-family: "Anton", sans-serif; font-size: 330px;
        line-height: 0.9; color: rgba(245, 183, 59, 0.12); white-space: nowrap;
      }

      /* 1 — the date */
      #s1-date { font-family: "Anton", sans-serif; font-size: 66px; letter-spacing: 0.08em; line-height: 1; }
      #s1-year { font-family: "DM Serif Display", serif; font-size: 330px; line-height: 0.86; letter-spacing: -0.03em; color: var(--gold); }
      #s1-where { font-size: 50px; color: var(--text-2); max-width: 760px; line-height: 1.15; }

      /* 2 — two kings */
      .pair { display: flex; gap: 32px; width: 100%; max-width: 858px; }
      .card { flex: 1; display: flex; flex-direction: column; gap: 14px; }
      .card .frame { height: 520px; }
      #s2-img-a { object-fit: contain; background: #e9e4d6; padding: 36px; }
      #s2-img-b { object-position: 72% 42%; }
      .role { font-size: 36px; color: var(--gold); line-height: 1.15; }
      #s2-foot { font-size: 34px; letter-spacing: 0.12em; margin-top: 10px; }

      /* 3 — the brother */
      #s3-main { font-size: 124px; line-height: 1.02; letter-spacing: -0.02em; max-width: 858px; margin-top: 60px; }
      #s3-fact { font-size: 44px; line-height: 1.2; color: var(--text-2); max-width: 820px; }

      /* 4 — the march */
      #s4-kb { position: absolute; inset: 0; }
      #s4-text { justify-content: center; align-items: flex-start; padding-top: 260px; padding-bottom: 700px; gap: 30px; }
      #s4-route { font-size: 40px; letter-spacing: 0.14em; }
      #s4-row { display: flex; align-items: baseline; gap: 22px; margin-left: -20px; }
      #s4-counter {
        font-family: "Anton", sans-serif; font-size: 300px; line-height: 1.12; color: var(--gold);
        font-variant-numeric: tabular-nums; width: 420px; text-align: right;
      }
      #s4-unit { font-family: "Anton", sans-serif; font-size: 96px; letter-spacing: 0.06em; color: var(--text); }
      #s4-days { font-size: 58px; color: var(--text); }

      /* 5 — the bridge */
      #s5-main { font-size: 132px; line-height: 1.02; letter-spacing: -0.02em; max-width: 858px; margin-top: 60px; }
      #s5-fact { font-size: 46px; line-height: 1.2; color: var(--text); max-width: 820px; }
      #s5-src { font-size: 32px; color: var(--text-2); }

      /* 6 — the manuscript */
      #s6-band {
        position: absolute; left: 0; right: 0; top: 380px; height: 600px; overflow: hidden;
        border-top: 3px solid var(--gold); border-bottom: 3px solid var(--gold);
      }
      #s6-kb { position: absolute; inset: 0; }
      #s6-kb img { width: 100%; height: 100%; object-fit: cover; object-position: 55% 40%; display: block; }
      #s6-sub {
        position: absolute; left: 72px; right: 150px; top: 1020px; font-size: 62px; line-height: 1.12;
        color: var(--text); text-align: center;
      }
      #s6-credit { position: absolute; left: 72px; right: 150px; top: 330px; text-align: center; font-size: 30px; color: var(--text-2); }

      /* 7 — epilogue */
      #s7-content { gap: 22px; }
      #s7-portrait { width: 620px; }
      #s7-portrait .frame { height: 560px; border-color: rgba(244, 246, 251, 0.55); }
      #s7-img { object-position: 58% 48%; }
      #s7-date { font-family: "DM Serif Display", serif; font-size: 88px; line-height: 1; }
      #s7-line { font-size: 46px; color: var(--text); max-width: 820px; line-height: 1.2; }
      #s7-line2 { font-size: 40px; color: var(--gold); max-width: 820px; line-height: 1.2; }

      /* 8 — end card */
      #s8-content { align-items: center; justify-content: center; text-align: center; padding: 200px 110px 420px 110px; gap: 24px; }
      #s8-icon { width: 180px; height: 180px; border-radius: 42px; box-shadow: 0 0 60px rgba(245, 183, 59, 0.35); display: block; }
      #s8-story { font-size: 68px; line-height: 1.1; max-width: 820px; }
      #s8-app { font-size: 34px; letter-spacing: 0.18em; color: var(--text-2); }
      #s8-name { font-family: "Anton", sans-serif; font-size: 92px; letter-spacing: 0.02em; line-height: 1; }
      #s8-tag { font-size: 44px; color: var(--gold); }
      #s8-cta {
        font-family: "Anton", sans-serif; font-size: 56px; letter-spacing: 0.14em; color: var(--void);
        background: var(--gold); border-radius: 999px; padding: 20px 70px; margin-top: 12px;
      }
      #s8-note { font-size: 40px; color: var(--text); }
      #s8-credit {
        position: absolute; left: 80px; right: 80px; top: 1440px; font-family: "DM Serif Display", serif;
        font-size: 23px; color: rgba(244, 246, 251, 0.62); text-align: center;
      }

      /* captions */
      #captions { position: absolute; left: 60px; right: 140px; top: 1180px; height: 200px; z-index: 50; pointer-events: none; }
      .cg {
        position: absolute; left: 0; right: 0; top: 0; text-align: center; font-family: "Anton", sans-serif;
        font-size: 80px; line-height: 1.05; letter-spacing: 0.01em; text-transform: uppercase; color: var(--text);
        text-shadow: 0 4px 22px rgba(0, 0, 0, 0.9), 0 0 3px rgba(0, 0, 0, 0.9); opacity: 0;
      }
      .cg .hl { color: var(--gold); }
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="main" data-start="0" data-duration="{{total}}" data-width="1080" data-height="1920">
      <!-- 1 ── ON THIS DAY, 1066 -->
      <div id="scene1" class="scene clip" data-start="{{scene1.start}}" data-duration="{{scene1.duration}}" data-track-index="1" style="z-index: 1">
        <div class="layer solid"></div>
        <div id="s1-kb" class="layer" data-layout-allow-overflow>
          <img class="cover" src="assets/arbo.jpg" alt="" style="object-position: 50% 62%" />
        </div>
        <div class="layer shade"></div>
        <div class="layer glow"></div>
        <div class="content">
          <div id="s1-kicker" class="kicker">On this day</div>
          <div id="s1-date">25 SEPTEMBER</div>
          <div id="s1-year">1066</div>
          <div id="s1-rule" class="rule"></div>
          <div id="s1-where" class="italic">Stamford Bridge, Yorkshire</div>
        </div>
      </div>

      <!-- 2 ── TWO KINGS -->
      <div id="scene2" class="scene clip" data-start="{{scene2.start}}" data-duration="{{scene2.duration}}" data-track-index="2" style="z-index: 2">
        <div id="s2-fade" class="layer">
          <div class="layer solid"></div>
          <div class="layer glow"></div>
          <div class="content">
            <div id="s2-kicker" class="kicker">Two kings</div>
            <div class="pair">
              <div id="s2-card-a" class="card">
                <div class="frame"><img id="s2-img-a" data-layout-allow-overflow src="assets/coin.png" alt="" /></div>
                <div class="label">Harald Hardrada</div>
                <div class="role italic">King of Norway · the invader</div>
              </div>
              <div id="s2-card-b" class="card">
                <div class="frame"><img id="s2-img-b" data-layout-allow-overflow src="assets/harold-crowned.png" alt="" /></div>
                <div class="label">Harold Godwinson</div>
                <div class="role italic">King of England</div>
              </div>
            </div>
            <div id="s2-foot" class="label">Hundreds of ships · September 1066</div>
          </div>
        </div>
      </div>

      <!-- 3 ── THE BROTHER (hard cut) -->
      <div id="scene3" class="scene clip" data-start="{{scene3.start}}" data-duration="{{scene3.duration}}" data-track-index="3" style="z-index: 3">
        <div class="layer solid"></div>
        <div id="s3-ghost" class="ghost" data-layout-ignore>BROTHER</div>
        <div class="content">
          <div id="s3-kicker" class="kicker">At his side</div>
          <div id="s3-main" class="serif">The English king’s own brother.</div>
          <div id="s3-rule" class="rule"></div>
          <div id="s3-fact" class="italic">Tostig Godwinson — exiled from Northumbria in 1065</div>
        </div>
      </div>

      <!-- 4 ── THE MARCH -->
      <div id="scene4" class="scene clip" data-start="{{scene4.start}}" data-duration="{{scene4.duration}}" data-track-index="4" style="z-index: 4">
        <div id="s4-fade" class="layer">
          <div class="layer solid"></div>
          <div id="s4-kb" data-layout-allow-overflow>
            <img class="cover" src="assets/arbo-d1.jpg" alt="" style="object-position: 30% 45%" />
          </div>
          <div class="layer shade"></div>
          <div id="s4-text" class="content" data-layout-allow-overlap>
            <div id="s4-route" class="label" data-layout-allow-overlap>London → Yorkshire</div>
            <div id="s4-row">
              <div id="s4-counter" data-layout-allow-overlap>0</div>
              <div id="s4-unit" data-layout-allow-overlap>MILES</div>
            </div>
            <div id="s4-days" class="italic" data-layout-allow-overlap>in four days</div>
          </div>
        </div>
      </div>

      <!-- 5 ── THE BRIDGE (hard cut) -->
      <div id="scene5" class="scene clip" data-start="{{scene5.start}}" data-duration="{{scene5.duration}}" data-track-index="5" style="z-index: 5">
        <div class="layer solid"></div>
        <div id="s5-ghost" class="ghost" data-layout-ignore>THE BRIDGE</div>
        <div class="content">
          <div id="s5-kicker" class="kicker">The bridge</div>
          <div id="s5-main" class="serif">One Viking. One axe.</div>
          <div id="s5-rule" class="rule"></div>
          <div id="s5-fact" class="italic">More than forty Englishmen cut down</div>
          <div id="s5-src" class="italic">— as the Anglo-Saxon Chronicle tells it</div>
        </div>
      </div>

      <!-- 6 ── THE MANUSCRIPT -->
      <div id="scene6" class="scene clip" data-start="{{scene6.start}}" data-duration="{{scene6.duration}}" data-track-index="6" style="z-index: 6">
        <div id="s6-fade" class="layer">
          <div class="layer solid"></div>
          <div class="layer glow"></div>
          <div id="s6-credit" class="italic">Matthew Paris, 13th century</div>
          <div id="s6-band">
            <div id="s6-kb" data-layout-allow-overflow><img src="assets/paris.png" alt="" /></div>
          </div>
          <div id="s6-sub" class="italic">Harald Hardrada and Tostig — both killed</div>
        </div>
      </div>

      <!-- 7 ── EPILOGUE -->
      <div id="scene7" class="scene clip" data-start="{{scene7.start}}" data-duration="{{scene7.duration}}" data-track-index="7" style="z-index: 7">
        <div id="s7-fade" class="layer">
          <div class="layer solid"></div>
          <div id="s7-content" class="content">
            <div id="s7-kicker" class="kicker" style="color: rgba(244, 246, 251, 0.8)">Nineteen days later</div>
            <div id="s7-portrait">
              <div class="frame"><img id="s7-img" data-layout-allow-overflow src="assets/harold-death.jpg" alt="" /></div>
            </div>
            <div id="s7-date">14 October 1066</div>
            <div id="s7-line" class="italic">Harold dies at the Battle of Hastings</div>
            <div id="s7-line2" class="italic">William the Conqueror takes the crown</div>
          </div>
        </div>
      </div>

      <!-- 8 ── END CARD -->
      <div id="scene8" class="scene clip" data-start="{{scene8.start}}" data-duration="{{scene8.duration}}" data-track-index="8" style="z-index: 8">
        <div id="s8-fade" class="layer">
          <div class="layer solid"></div>
          <div class="layer" style="opacity: 0.14">
            <img class="cover" src="assets/arbo-d2.jpg" alt="" style="object-position: 50% 50%" />
          </div>
          <div class="layer glow"></div>
          <div id="s8-content" class="content">
            <img id="s8-icon" src="assets/icon.png" alt="" />
            <div id="s8-story" class="serif">Every day has a story like this.</div>
            <div id="s8-app" class="label">Our app</div>
            <div id="s8-name">HISTORY UNLOCKED</div>
            <div id="s8-tag" class="italic">coming soon to Google Play</div>
            <div id="s8-cta">{{endCard.pill}}</div>
            <div id="s8-note" class="italic">{{endCard.note}}</div>
          </div>
          <div id="s8-credit">
            Images: Peter Nicolai Arbo (1870), Matthew Paris (13th c.), Bayeux Tapestry, coin of Harald III · public domain.
            Music: Chopin, Nocturne in C minor · public domain. Sources: Wikipedia.
          </div>
        </div>
      </div>

      <div id="captions" class="clip" data-start="0" data-duration="{{captions.duration}}" data-track-index="10"></div>
      <audio id="soundtrack" data-start="0" data-duration="{{total}}" data-track-index="0" src="mix.wav" data-volume="1"></audio>
    </div>

    <script>
      var T = /*TIMINGS*/ null;
      var G = T.seg;
      var S = T.scene;
      function within(id, f) { return G[id].start + (G[id].end - G[id].start) * f; }

      var KEY = {
        1066: 1, VIKING: 1, VIKINGS: 1, HARDRADA: 1, NORWAY: 1, HAROLD: 1, TOSTIG: 1, BROTHER: 1,
        185: 1, AXE: 1, FORTY: 1, DEAD: 1, HASTINGS: 1, WILLIAM: 1, CONQUEROR: 1, BRIDGE: 1, SHIPS: 1,
      };

      function groupsOf(phrase) {
        var words = phrase.show.split(/\s+/);
        var parts = [], part = [];
        words.forEach(function (w, i) {
          part.push(w);
          if (/[.,?!]$/.test(w) || i === words.length - 1) { parts.push(part); part = []; }
        });
        var groups = [];
        parts.forEach(function (p) {
          var chunks = Math.ceil(p.length / 4), base = Math.floor(p.length / chunks), extra = p.length % chunks, at = 0;
          for (var c = 0; c < chunks; c++) { var size = base + (c < extra ? 1 : 0); groups.push(p.slice(at, at + size)); at += size; }
        });
        var total = groups.reduce(function (n, g) { return n + g.join(" ").length; }, 0);
        var span = phrase.end - phrase.start, t = phrase.start;
        return groups.map(function (g) { var d = (span * g.join(" ").length) / total; var o = { words: g, start: t, end: t + d }; t += d; return o; });
      }

      var GROUPS = [];
      T.captions.forEach(function (p) { GROUPS = GROUPS.concat(groupsOf(p)); });
      var box = document.getElementById("captions");
      GROUPS.forEach(function (g, i) {
        var el = document.createElement("div");
        el.className = "cg";
        el.id = "cg-" + i;
        el.innerHTML = g.words.map(function (w) {
          var bare = w.toUpperCase().replace(/[.,?!’']+$/, "").replace(/’S$|'S$/, "");
          return KEY[bare] ? '<span class="hl">' + w + "</span>" : w;
        }).join(" ");
        box.appendChild(el);
        if (window.__hyperframes && window.__hyperframes.fitTextFontSize) {
          var fit = window.__hyperframes.fitTextFontSize(g.words.join(" ").toUpperCase(), {
            fontFamily: "Anton", fontWeight: 400, maxWidth: 860, baseFontSize: 80, minFontSize: 54,
          });
          el.style.fontSize = fit.fontSize + "px";
        }
      });

      var tl = gsap.timeline({ paused: true });

      // 1 — date over the painting
      tl.fromTo("#s1-kb", { scale: 1.16 }, { scale: 1.0, duration: S.scene1.duration, ease: "none" }, 0);
      tl.fromTo("#s1-kicker", { opacity: 0, x: -50 }, { opacity: 1, x: 0, duration: 0.45, ease: "power3.out" }, 0.15);
      tl.fromTo("#s1-date", { opacity: 0, scale: 1.18 }, { opacity: 1, scale: 1, duration: 0.7, ease: "expo.out", transformOrigin: "0% 50%" }, 0.3);
      tl.fromTo("#s1-year", { opacity: 0, scale: 1.3 }, { opacity: 1, scale: 1, duration: 0.55, ease: "back.out(1.6)", transformOrigin: "0% 60%" }, 0.45);
      tl.fromTo("#s1-rule", { scaleX: 0 }, { scaleX: 1, duration: 0.8, ease: "power4.out", transformOrigin: "0% 50%" }, 0.85);
      tl.fromTo("#s1-where", { opacity: 0, y: 24 }, { opacity: 1, y: 0, duration: 0.6, ease: "sine.out" }, 1.15);

      // 2 — two kings arrive from opposite sides
      var t2 = S.scene2.start;
      tl.fromTo("#s2-fade", { opacity: 0 }, { opacity: 1, duration: 0.3, ease: "power1.out" }, t2);
      tl.fromTo("#s2-kicker", { opacity: 0, y: -40 }, { opacity: 1, y: 0, duration: 0.6, ease: "expo.out" }, t2 + 0.15);
      tl.fromTo("#s2-card-a", { opacity: 0, x: -90 }, { opacity: 1, x: 0, duration: 0.7, ease: "power4.out" }, t2 + 0.25);
      tl.fromTo("#s2-card-b", { opacity: 0, x: 90 }, { opacity: 1, x: 0, duration: 0.7, ease: "power3.out" }, t2 + 1.1);
      tl.fromTo("#s2-img-a", { scale: 1.0 }, { scale: 1.06, duration: S.scene2.duration, ease: "none" }, t2);
      tl.fromTo("#s2-img-b", { scale: 1.1 }, { scale: 1.0, duration: S.scene2.duration, ease: "none" }, t2);
      tl.fromTo("#s2-foot", { opacity: 0, y: 24 }, { opacity: 1, y: 0, duration: 0.5, ease: "circ.out" }, within("s2", 0.7));

      // 3 — hard cut: the brother
      var t3 = S.scene3.start;
      tl.fromTo("#s3-ghost", { x: 0 }, { x: -220, duration: S.scene3.duration, ease: "none" }, t3);
      tl.fromTo("#s3-kicker", { opacity: 0 }, { opacity: 1, duration: 0.25, ease: "power2.out" }, t3 + 0.05);
      tl.fromTo("#s3-main", { opacity: 0, y: 70 }, { opacity: 1, y: 0, duration: 0.8, ease: "expo.out" }, within("s3", 0.4));
      tl.fromTo("#s3-rule", { scaleX: 0 }, { scaleX: 1, duration: 0.6, ease: "power4.out", transformOrigin: "0% 50%" }, within("s3", 0.6));
      tl.fromTo("#s3-fact", { opacity: 0, x: -30 }, { opacity: 1, x: 0, duration: 0.6, ease: "sine.out" }, within("s3", 0.8));

      // 4 — the march: the miles count as they are said
      var t4 = S.scene4.start;
      tl.fromTo("#s4-fade", { opacity: 0 }, { opacity: 1, duration: 0.35, ease: "power1.out" }, t4);
      tl.fromTo("#s4-kb", { scale: 1.22 }, { scale: 1.04, duration: S.scene4.duration, ease: "power1.out" }, t4);
      tl.fromTo("#s4-route", { opacity: 0, x: -40 }, { opacity: 1, x: 0, duration: 0.45, ease: "power3.out" }, t4 + 0.2);
      tl.fromTo("#s4-row", { opacity: 0, scale: 0.85 }, { opacity: 1, scale: 1, duration: 0.4, ease: "back.out(1.7)", transformOrigin: "0% 50%" }, t4 + 0.3);
      var miles = { v: 0 };
      var counter = document.getElementById("s4-counter");
      function showMiles() { counter.textContent = String(Math.round(miles.v)); }
      var countFrom = within("s4a", 0.3);
      var countTo = within("s4a", 0.72);
      tl.fromTo(miles, { v: 0 }, { v: 185, duration: countTo - countFrom, ease: "power2.out", onUpdate: showMiles, onComplete: showMiles }, countFrom);
      tl.fromTo("#s4-days", { opacity: 0, y: 24 }, { opacity: 1, y: 0, duration: 0.5, ease: "sine.out" }, within("s4a", 0.8));

      // 5 — hard cut: the bridge
      var t5 = S.scene5.start;
      tl.fromTo("#s5-ghost", { x: 0 }, { x: -260, duration: S.scene5.duration, ease: "none" }, t5);
      tl.fromTo("#s5-kicker", { opacity: 0 }, { opacity: 1, duration: 0.25, ease: "power2.out" }, t5 + 0.05);
      tl.fromTo("#s5-main", { opacity: 0, y: 70 }, { opacity: 1, y: 0, duration: 0.8, ease: "expo.out" }, within("s5a", 0.35));
      tl.fromTo("#s5-rule", { scaleX: 0 }, { scaleX: 1, duration: 0.6, ease: "power4.out", transformOrigin: "0% 50%" }, G.s5b.start);
      tl.fromTo("#s5-fact", { opacity: 0, x: -30 }, { opacity: 1, x: 0, duration: 0.6, ease: "sine.out" }, within("s5b", 0.12));
      tl.fromTo("#s5-src", { opacity: 0 }, { opacity: 1, duration: 0.6, ease: "sine.out" }, within("s5b", 0.4));

      // 6 — the manuscript
      var t6 = S.scene6.start;
      tl.fromTo("#s6-fade", { opacity: 0 }, { opacity: 1, duration: 0.35, ease: "power1.out" }, t6);
      tl.fromTo("#s6-kb", { scale: 1.3, opacity: 0 }, { scale: 1.04, opacity: 1, duration: 0.9, ease: "expo.out" }, t6 + 0.05);
      tl.fromTo("#s6-credit", { opacity: 0 }, { opacity: 1, duration: 0.5, ease: "sine.out" }, t6 + 0.4);
      tl.fromTo("#s6-sub", { opacity: 0, y: 30 }, { opacity: 1, y: 0, duration: 0.6, ease: "power2.out" }, within("s6", 0.35));

      // 7 — epilogue, slower
      var t7 = S.scene7.start;
      tl.fromTo("#s7-fade", { opacity: 0 }, { opacity: 1, duration: 0.6, ease: "sine.inOut" }, t7);
      tl.fromTo("#s7-kicker", { opacity: 0 }, { opacity: 1, duration: 0.6, ease: "sine.out" }, t7 + 0.2);
      tl.fromTo("#s7-portrait", { opacity: 0 }, { opacity: 1, duration: 0.9, ease: "sine.out" }, t7 + 0.3);
      tl.fromTo("#s7-img", { scale: 1.0 }, { scale: 1.07, duration: S.scene7.duration, ease: "none" }, t7);
      tl.fromTo("#s7-date", { opacity: 0 }, { opacity: 1, duration: 0.9, ease: "sine.out" }, G.s7b.start);
      tl.fromTo("#s7-line", { opacity: 0 }, { opacity: 1, duration: 0.9, ease: "sine.out" }, within("s7b", 0.3));
      tl.fromTo("#s7-line2", { opacity: 0, y: 16 }, { opacity: 1, y: 0, duration: 0.8, ease: "sine.out" }, within("s7b", 0.6));

      // 8 — end card
      var t8 = S.scene8.start;
      tl.fromTo("#s8-fade", { opacity: 0 }, { opacity: 1, duration: 0.3, ease: "power1.out" }, t8);
      tl.fromTo("#s8-icon", { opacity: 0, scale: 0.6 }, { opacity: 1, scale: 1, duration: 0.6, ease: "back.out(1.8)" }, t8 + 0.15);
      tl.fromTo("#s8-story", { opacity: 0, y: 30 }, { opacity: 1, y: 0, duration: 0.7, ease: "power3.out" }, G.s8a.start + 0.05);
      tl.fromTo("#s8-app", { opacity: 0 }, { opacity: 1, duration: 0.5, ease: "sine.out" }, G.s8a.end - 0.4);
      tl.fromTo("#s8-name", { opacity: 0, scale: 1.2 }, { opacity: 1, scale: 1, duration: 0.7, ease: "expo.out" }, G.s8a.end - 0.3);
      tl.fromTo("#s8-tag", { opacity: 0 }, { opacity: 1, duration: 0.6, ease: "sine.out" }, G.s8a.end);
      tl.fromTo("#s8-cta", { opacity: 0, scale: 0.8 }, { opacity: 1, scale: 1, duration: 0.5, ease: "back.out(2)" }, G.s8b.start);
      tl.fromTo("#s8-cta", { scale: 1 }, { scale: 1.07, duration: 0.45, ease: "sine.inOut", yoyo: true, repeat: 3, immediateRender: false }, G.s8b.start + 0.55);
      tl.fromTo("#s8-note", { opacity: 0, y: 16 }, { opacity: 1, y: 0, duration: 0.5, ease: "sine.out" }, within("s8b", 0.35));
      tl.fromTo("#s8-credit", { opacity: 0 }, { opacity: 1, duration: 0.5, ease: "sine.out" }, G.s8a.end + 0.2);
      tl.fromTo("#s8-content", { opacity: 1 }, { opacity: 0, duration: 0.4, ease: "power2.in" }, T.total - 0.45);

      // captions
      GROUPS.forEach(function (g, i) {
        var sel = "#cg-" + i;
        tl.fromTo(sel, { opacity: 0, scale: 0.9 }, { opacity: 1, scale: 1, duration: 0.14, ease: "back.out(1.7)" }, g.start);
        tl.to(sel, { opacity: 0, duration: 0.1, ease: "power2.in" }, g.end - 0.1);
        tl.set(sel, { opacity: 0, visibility: "hidden" }, g.end);
      });

      window.__timelines["main"] = tl;
      tl.seek(0);
    </script>
  </body>
</html>
