/**
 * Written headlines for the cornerstones — the events that lead their day.
 *
 * Without these a cornerstone's card took its article's opening sentence,
 * which is an encyclopedia definition, not a headline, and was usually cut at
 * 90 characters: "Apollo 13 (April 11–17, 1970) was the seventh crewed mission in the
 * Apollo space program…". 52 of the 147 leads ended in an ellipsis, and the
 * lead is the first thing a reader sees on the date.
 *
 * Rules, enforced by tests/cornerstoneHeadlines.test.ts:
 *  - one finished sentence, past tense, what HAPPENED on the date
 *  - at most 90 characters, so the card never cuts it
 *  - no claim that is not in the article; numbers only where the article
 *    states them, and hedged where it hedges ("hundreds of thousands")
 *
 * Keyed "MM-DD|year" — unique across the list, and stable when an image
 * override re-points an event's wikiTitle.
 */
export const CORNERSTONE_HEADLINES: Record<string, string> = {
  '01-01|1863': "Lincoln's Emancipation Proclamation declared enslaved people in the Confederacy free",
  '01-01|1959': "Batista fled Cuba, and Fidel Castro's revolution took power",
  '01-06|2021': 'A mob stormed the US Capitol to stop the certification of the 2020 election',
  '01-27|1945': 'Soviet troops liberated Auschwitz, the largest Nazi death camp',
  '01-28|1986': 'Space Shuttle Challenger broke apart 73 seconds after launch, killing all seven crew',
  '01-30|1948': 'Mahatma Gandhi was assassinated in New Delhi by a Hindu nationalist',
  '02-01|2003': 'Space Shuttle Columbia broke apart on re-entry, killing all seven astronauts',
  '02-02|1943': 'The Battle of Stalingrad ended with the surrender of the last German forces',
  '02-11|1979': 'The Iranian Revolution toppled the monarchy and brought Khomeini to power',
  '02-11|1990': 'Nelson Mandela walked free after 27 years in prison',
  '02-24|2022': 'Russia launched a full-scale invasion of Ukraine',
  '02-27|1933': 'The Reichstag in Berlin was set on fire, and the Nazis used it to seize emergency powers',
  '03-03|1878': 'The Treaty of San Stefano ended the Russo-Turkish War and restored a Bulgarian state',
  '03-05|1770': 'British soldiers fired on a crowd in Boston, killing five colonists',
  '03-10|1876': 'Alexander Graham Bell made the first successful telephone call',
  '03-11|2011': 'A magnitude 9 earthquake and tsunami struck Japan, triggering the Fukushima disaster',
  '03-11|2020': 'The World Health Organization declared COVID-19 a pandemic',
  '03-12|1930': 'Gandhi set out on the Salt March, defying British rule over salt',
  '03-15|-44': 'Julius Caesar was stabbed to death by senators on the Ides of March',
  '03-20|2003': 'A US-led coalition invaded Iraq, beginning the Iraq War',
  '03-25|1957': 'Six nations signed the Treaty of Rome, founding the European Economic Community',
  '04-04|1949': 'Twelve nations signed the North Atlantic Treaty, founding NATO',
  '04-04|1968': 'Martin Luther King Jr. was assassinated on a motel balcony in Memphis',
  '04-07|1994': 'The Rwandan genocide began — hundreds of thousands were killed in about 100 days',
  '04-09|1865': 'Robert E. Lee surrendered at Appomattox, effectively ending the American Civil War',
  '04-10|1998': 'The Good Friday Agreement was signed, ending three decades of conflict in Northern Ireland',
  '04-11|1970': 'Apollo 13 lifted off — two days later an explosion turned it into a fight for survival',
  '04-12|1955': "Jonas Salk's polio vaccine was declared safe and effective",
  '04-12|1961': 'Yuri Gagarin became the first human to fly into space',
  '04-13|1204': 'Fourth Crusade armies sacked Constantinople, the greatest Christian city of the age',
  '04-14|1865': "Abraham Lincoln was shot at Ford's Theatre in Washington",
  '04-14|2003': 'The Human Genome Project announced the complete map of human DNA',
  '04-15|1912': 'RMS Titanic sank in the North Atlantic Ocean on 15 April 1912',
  '04-18|1955': 'Twenty-nine Asian and African nations met at Bandung to oppose colonialism',
  '04-24|1990': 'The Hubble Space Telescope was launched aboard Space Shuttle Discovery',
  '04-25|1974': "Portugal's Carnation Revolution overthrew the dictatorship almost without bloodshed",
  '04-26|1986': 'Reactor 4 of the Chernobyl nuclear plant exploded in the worst nuclear disaster in history',
  '04-27|1994': 'South Africa held its first election open to all races, and Mandela won',
  '04-30|1945': 'Adolf Hitler killed himself in his Berlin bunker',
  '04-30|1975': 'Saigon fell to North Vietnamese forces, ending the Vietnam War',
  '05-02|2011': 'US special forces killed Osama bin Laden in Abbottabad, Pakistan',
  '05-06|1937': 'The airship Hindenburg burst into flames while landing in New Jersey',
  '05-08|1945': "Germany's surrender took effect — Victory in Europe Day",
  '05-08|1980': 'The World Health Assembly declared smallpox eradicated',
  '05-10|1869': "The golden spike completed America's first transcontinental railroad",
  '05-14|1948': 'David Ben-Gurion proclaimed the State of Israel',
  '05-21|1927': 'Charles Lindbergh landed in Paris after the first solo nonstop flight across the Atlantic',
  '05-25|2020': 'George Floyd was murdered by a Minneapolis police officer, setting off worldwide protests',
  '05-29|1453': 'Constantinople fell to the Ottomans, ending the Byzantine Empire',
  '05-29|1953': 'Edmund Hillary and Tenzing Norgay became the first to reach the summit of Everest',
  '06-04|1942': 'At Midway, US aircraft sank four Japanese carriers in a battle that turned the Pacific war',
  '06-04|1989': 'Troops opened fire on protesters around Tiananmen Square in Beijing',
  '06-05|1967': 'The Six-Day War began between Israel and Egypt, Jordan and Syria',
  '06-06|1944': 'D-Day: Allied forces landed on the beaches of Normandy',
  '06-12|1987': 'At the Brandenburg Gate, Reagan urged: "Mr. Gorbachev, tear down this wall!"',
  '06-15|1215': 'King John sealed Magna Carta at Runnymede',
  '06-16|1963': 'Valentina Tereshkova became the first woman in space',
  '06-16|1976': 'Police opened fire on schoolchildren protesting in Soweto, South Africa',
  '06-18|1815': 'Napoleon was finally defeated at the Battle of Waterloo',
  '06-19|1865': 'Union troops announced in Texas that all enslaved people were free — Juneteenth',
  '06-22|1941': 'Nazi Germany invaded the Soviet Union in Operation Barbarossa',
  '06-23|2016': 'The United Kingdom voted to leave the European Union',
  '06-25|1950': 'North Korea invaded the South, starting the Korean War',
  '06-28|1914': 'Archduke Franz Ferdinand was assassinated in Sarajevo, sparking World War I',
  '06-28|1919': 'The Treaty of Versailles was signed, formally ending World War I',
  '07-04|1776': 'The Continental Congress adopted the Declaration of Independence',
  '07-05|1948': 'Britain’s National Health Service opened, free at the point of use, under Aneurin Bevan',
  '07-05|1996': 'Dolly the sheep was born — the first mammal cloned from an adult cell',
  '07-11|1995': 'Bosnian Serb forces began the massacre of over 8,000 Bosniaks at Srebrenica',
  '07-13|1878': 'The Treaty of Berlin redrew the Balkans and split the Bulgaria of San Stefano in three',
  '07-14|1789': 'Parisians stormed the Bastille, the spark of the French Revolution',
  '07-16|1054': 'Papal envoys excommunicated the Patriarch of Constantinople — the Great Schism',
  '07-16|1945': 'The first atomic bomb was detonated in the New Mexico desert',
  '07-17|1975': 'An American Apollo and a Soviet Soyuz docked in orbit',
  '07-17|1998': 'The Rome Statute was adopted, creating the International Criminal Court',
  '07-20|1969': 'Apollo 11 landed on the Moon, and Neil Armstrong became the first person to walk on it',
  '07-25|1978': 'Louise Brown, the first person conceived by IVF, was born in Oldham, England',
  '08-01|1834': 'The Slavery Abolition Act took effect across most of the British Empire',
  '08-02|-216': 'Hannibal annihilated a much larger Roman army at Cannae',
  '08-02|1990': 'Iraq invaded Kuwait, leading to the Gulf War',
  '08-06|1945': 'The United States dropped an atomic bomb on Hiroshima',
  '08-06|1991': 'Tim Berners-Lee made the World Wide Web public',
  '08-08|1588': 'The English fleet attacked the Spanish Armada off Gravelines',
  '08-13|1961': 'East Germany began building the Berlin Wall overnight',
  '08-15|1947': 'India won independence as British India was partitioned into two states',
  '08-23|1939': 'Nazi Germany and the Soviet Union signed the Molotov–Ribbentrop Pact',
  '08-24|79': 'Mount Vesuvius erupted, burying Pompeii and Herculaneum',
  '08-26|1920': 'The 19th Amendment took effect, giving American women the vote',
  '08-28|1963': 'Martin Luther King Jr. delivered his "I Have a Dream" speech in Washington',
  '08-29|1526': 'The Ottomans crushed the Hungarian army at Mohács, and King Louis II died fleeing',
  '08-31|1980': 'The Gdańsk Agreement was signed, and Solidarity became the Eastern Bloc’s first free union',
  '09-01|1939': 'Germany invaded Poland, starting World War II in Europe',
  '09-02|-31': 'Octavian defeated Antony and Cleopatra at the naval Battle of Actium',
  '09-02|1945': 'Japan formally surrendered aboard USS Missouri, ending World War II',
  '09-05|1977': 'NASA launched Voyager 1, now the farthest human-made object from Earth',
  '09-06|1885': 'Eastern Rumelia united with the Principality of Bulgaria',
  '09-08|1941': 'German forces cut off Leningrad, beginning a siege that lasted 872 days',
  '09-09|9': 'Germanic tribes destroyed three Roman legions in the Teutoburg Forest',
  '09-11|2001': 'Terrorists crashed hijacked airliners into the World Trade Center and the Pentagon',
  '09-12|1683': 'A Polish-led relief army broke the Ottoman siege of Vienna',
  '09-15|2008': 'Lehman Brothers filed for bankruptcy, the largest in US history',
  '09-17|1787': 'The US Constitution was signed in Philadelphia',
  '09-17|1978': 'Egypt and Israel signed the Camp David Accords',
  '09-22|1908': 'Bulgaria declared full independence from the Ottoman Empire',
  '09-28|1928': 'Alexander Fleming discovered penicillin in a mould-contaminated dish',
  '09-30|1938': "The Munich Agreement handed Czechoslovakia's Sudetenland to Hitler",
  '10-01|1908': 'Ford released the Model T, the car that put America on wheels',
  '10-01|1949': "Mao Zedong proclaimed the People's Republic of China",
  '10-04|1957': 'The Soviet Union launched Sputnik 1, the first artificial satellite',
  '10-06|1973': 'Egypt and Syria attacked Israel on Yom Kippur, starting the Yom Kippur War',
  '10-07|1571': 'A Holy League fleet destroyed the Ottoman navy at Lepanto',
  '10-12|1492': 'Christopher Columbus reached the Americas, landing in the Bahamas',
  '10-14|1066': 'William of Normandy defeated King Harold at the Battle of Hastings',
  '10-16|1934': "China's Communists began the Long March, a year-long retreat across the country",
  '10-16|1962': 'The Cuban Missile Crisis began: Kennedy was shown photos of Soviet missiles in Cuba',
  '10-19|1781': 'British forces surrendered at Yorktown, deciding the American Revolutionary War',
  '10-21|1805': "Nelson's fleet defeated France and Spain at Trafalgar, and Nelson was killed",
  '10-24|1945': 'The United Nations came into existence',
  '10-29|1929': 'Black Tuesday: the Wall Street stock market crashed',
  '10-29|1956': 'Israel invaded Sinai, starting the Suez Crisis',
  '10-31|1517': 'Martin Luther published his Ninety-five Theses, starting the Reformation',
  '11-04|1979': 'Iranian students seized the US embassy in Tehran, beginning a 444-day hostage crisis',
  '11-05|1605': 'The Gunpowder Plot to blow up Parliament was foiled, and Guy Fawkes was arrested',
  '11-07|1917': 'The Bolsheviks seized power in Petrograd in the October Revolution',
  '11-08|1895': 'Wilhelm Röntgen discovered X-rays',
  '11-09|1938': 'Kristallnacht: Nazi mobs attacked Jewish homes, shops and synagogues across Germany',
  '11-09|1989': 'The Berlin Wall fell as East Germany opened its border',
  '11-11|1918': 'The Armistice took effect at 11 a.m., ending the fighting of World War I',
  '11-17|1989': 'Students marched in Prague, beginning the Velvet Revolution',
  '11-19|1863': 'Abraham Lincoln delivered the Gettysburg Address',
  '11-21|1995': 'The Dayton Agreement was initialled, ending the war in Bosnia',
  '11-22|1963': 'President John F. Kennedy was assassinated in Dallas',
  '11-24|1859': 'Charles Darwin published On the Origin of Species',
  '11-27|1095': 'Pope Urban II called for the First Crusade at Clermont',
  '12-01|1955': 'Rosa Parks refused to give up her bus seat in Montgomery, Alabama',
  '12-02|1805': 'Napoleon won his greatest victory at Austerlitz',
  '12-02|1942': 'Chicago Pile-1 achieved the first controlled nuclear chain reaction',
  '12-07|1941': 'Japan attacked the US fleet at Pearl Harbor',
  '12-10|1948': 'The UN adopted the Universal Declaration of Human Rights',
  '12-11|1997': 'The Kyoto Protocol was adopted to cut greenhouse gas emissions',
  '12-12|2015': 'Nearly every nation agreed to the Paris Agreement on climate change',
  '12-14|1911': 'Roald Amundsen’s party became the first people to reach the South Pole',
  '12-16|1773': 'Colonists dumped British tea into Boston Harbor in the Boston Tea Party',
  '12-17|1903': 'The Wright brothers made the first powered airplane flights at Kitty Hawk',
  '12-26|1991': 'The Soviet Union was formally dissolved',
  '12-26|2004': 'An undersea earthquake off Sumatra unleashed the Indian Ocean tsunami',
  '12-29|1890': 'US soldiers killed hundreds of Lakota at Wounded Knee',
};

export const headlineKey = (dateKey: string, year: number) => `${dateKey}|${year}`;
