/**
 * Written headlines for the events a FREE reader is shown — the three a day
 * `planDeck` picks for the free tier — wherever the feed sentence could not be
 * cut to 90 characters without an ellipsis (318 of 1,098 on 27 September).
 *
 * Same rules as cornerstone-headlines.ts: one finished sentence of what
 * happened, at most 90 characters, nothing the source does not say. Written
 * from the feed's own sentence (pipeline/.feed-cache), or where that was
 * missing from the event's facts. Keyed by event id; the lite builder and
 * apply-cornerstone-headlines.ts both read it, so a rebuild keeps them.
 */
export const WRITTEN_HEADLINES: Record<string, string> = {
  "evt-01-02-2024-haneda-airport": "Landing at Haneda, Japan Airlines Flight 516 collided with a Dash 8, killing five people",
  "evt-01-03-1777-american-revolutionary-war": "George Washington's army defeated the British at the Battle of Princeton",
  "evt-01-04-1853-solomon-northup": "Solomon Northup regained his freedom after 12 years of slavery in the American South",
  "evt-01-05-1991-embassy-of-the-united-states-mogadishu": "The US embassy in Mogadishu was evacuated by helicopter as the Somali Civil War raged",
  "evt-01-06-2017-fort-lauderdale-airport-shooting": "A gunman killed five people at Fort Lauderdale–Hollywood International Airport",
  "evt-01-07-2020-2019-20-puerto-rico-earthquakes": "The 2019–20 Puerto Rico earthquakes killed four people and injured nine",
  "evt-01-08-1918-woodrow-wilson": "Woodrow Wilson announced his Fourteen Points for peace after World War I",
  "evt-01-09-2015-charlie-hebdo-shooting": "The Charlie Hebdo gunmen were killed after a siege; a second siege hit a Jewish market",
  "evt-01-09-1991-iraq": "US and Iraqi envoys met in Geneva in a last attempt to avoid the Gulf War",
  "evt-01-10-1917-imperial-trans-antarctic-expedition": "Seven survivors of the Ross Sea party were rescued after two years stranded in Antarctica",
  "evt-01-11-1994-republic-of-ireland": "Ireland ended its 15-year broadcasting ban on the IRA and Sinn Féin",
  "evt-01-11-1961-university-of-georgia": "Students rioted at the University of Georgia against the admission of two Black students",
  "evt-01-11-1996-space-shuttle-program": "Space Shuttle Endeavour launched on STS-72, the 74th Space Shuttle mission",
  "evt-01-12-1777-mission-santa-clara-de-asis": "Franciscans founded Mission Santa Clara de Asís, the origin of the city of Santa Clara",
  "evt-01-13-1915-1915-avezzano-earthquake": "An earthquake in Italy's Province of L'Aquila killed about 30,000 people",
  "evt-01-13-2003-208996-achlys": "Astronomers discovered the trans-Neptunian object 208996 Achlys in the Kuiper belt",
  "evt-01-14-1969-1969-uss-enterprise-fire": "A fire aboard the carrier USS Enterprise killed 28 sailors and destroyed 15 aircraft",
  "evt-01-16-2016-2016-ouagadougou-attacks": "Terrorist attacks on a hotel and a restaurant in Ouagadougou, Burkina Faso, killed 23",
  "evt-01-18-1983-international-olympic-committee": "The IOC gave commemorative medals to Jim Thorpe's family, 30 years after his death",
  "evt-01-19-1981-iran-hostage-crisis": "The US and Iran signed the agreement to free 52 American hostages after 14 months",
  "evt-01-20-2009-iceland": "The 2009 Icelandic financial crisis protests began",
  "evt-01-21-1997-united-states-house-of-representatives": "The US House reprimanded Newt Gingrich, the first Speaker ever disciplined for ethics",
  "evt-01-21-2025-2025-kartalkaya-hotel-fire": "A fire at a hotel in Turkey's Kartalkaya ski resort killed 78 people",
  "evt-01-22-1973-supreme-court-of-the-united-states": "In Roe v. Wade, the US Supreme Court struck down laws restricting early abortion",
  "evt-01-22-1987-philippines": "Philippine forces fired on demonstrators near Malacañang Palace in Manila, killing 13",
  "evt-01-25-1990-avianca-flight-052": "Avianca Flight 52 ran out of fuel near New York's JFK Airport and crashed, killing 73",
  "evt-01-27-1980-iran-hostage-crisis": "Six American diplomats escaped Iran with the help of Canadian officials",
  "evt-01-27-2013-kiss-nightclub-fire": "A nightclub fire in Santa Maria, Brazil, killed 242 people",
  "evt-01-28-1521-charles-v-holy-roman-emperor": "Charles V opened the Diet of Worms with the estates of the Holy Roman Empire",
  "evt-01-28-2026-2026-rubaya-mines-collapses": "A collapse at the Rubaya mines in DR Congo killed at least 400 people",
  "evt-01-29-2025-american-eagle-airline-brand": "An American Eagle jet and an Army helicopter collided over the Potomac, killing all 67",
  "evt-01-30-1968-vietnam-war": "The Viet Cong and North Vietnam launched the Tet Offensive across South Vietnam",
  "evt-01-31-1961-nasa": "The chimpanzee Ham flew aboard Mercury-Redstone 2, the first hominid launched into space",
  "evt-01-31-2020-united-kingdom": "The United Kingdom left the European Union after 47 years of membership",
  "evt-02-02-2025-slovenia": "Luka Dončić was traded from Dallas to the Los Angeles Lakers for Anthony Davis",
  "evt-02-03-1852-argentine-confederation": "Brazil, Uruguay and two Argentine provinces defeated the Argentine Confederation",
  "evt-02-04-1997-lebanon": "Two Israeli troop helicopters collided over northern Galilee, killing 73",
  "evt-02-05-2020-pegasus-airlines-flight-2193": "Pegasus Airlines Flight 2193 overshot the runway in Istanbul, killing three",
  "evt-02-05-1869-moliagul": "Prospectors in Australia found the Welcome Stranger, the largest alluvial gold nugget ever",
  "evt-02-05-1917-united-states-congress": "Congress overrode Wilson's veto to pass the Immigration Act of 1917, barring much of Asia",
  "evt-02-06-2023-2023-turkey-syria-earthquakes": "Two earthquakes of magnitude 7.8 and 7.5 struck Turkey and Syria, killing 57,658 people",
  "evt-02-07-1865-seattle": "Seattle passed an ordinance expelling Native Americans from the new town",
  "evt-02-08-2013-february-2013-north-american-blizzard": "A blizzard killed at least 18 and cut power to hundreds of thousands in the US and Canada",
  "evt-02-09-1971-1971-san-fernando-earthquake": "A magnitude 6.6 earthquake struck the San Fernando Valley near Los Angeles",
  "evt-02-09-1825-united-states-electoral-college": "The House elected John Quincy Adams president after no candidate won a majority",
  "evt-02-10-1355-university-of-oxford": "A tavern dispute in Oxford became a town-versus-students riot that left about 90 dead",
  "evt-02-10-2016-south-korea": "South Korea halted the Kaesong industrial complex it ran jointly with North Korea",
  "evt-02-12-2004-san-francisco": "San Francisco began issuing marriage licenses to same-sex couples",
  "evt-02-12-2019-north-macedonia": "The Republic of Macedonia renamed itself North Macedonia, ending its dispute with Greece",
  "evt-02-13-2007-taiwan": "Ma Ying-jeou resigned as Kuomintang chairman after being indicted for embezzlement",
  "evt-02-13-2012-european-space-agency": "The European Space Agency launched the first Vega rocket from French Guiana",
  "evt-02-14-2011-arab-spring": "Bahraini youths began an uprising against the government on the Day of Rage",
  "evt-02-15-2018-2014-2016-oromo-protests": "Hailemariam Desalegn announced his resignation as prime minister of Ethiopia",
  "evt-02-16-2000-emery-worldwide-airlines-flight-17": "Emery Worldwide Airlines Flight 17 crashed near Sacramento, killing all three aboard",
  "evt-02-16-1922-byblos": "A landslide in Byblos revealed a sarcophagus in a Bronze Age necropolis",
  "evt-02-17-1996-nasa": "The NEAR Shoemaker probe launched on the first mission to orbit and land on an asteroid",
  "evt-02-17-2011-bahrain": "Bahraini security forces raided protesters at Pearl Roundabout — Bloody Thursday",
  "evt-02-18-1991-provisional-irish-republican-army": "The IRA exploded bombs at Paddington and Victoria stations in London",
  "evt-02-19-2002-nasa": "NASA's Mars Odyssey began mapping the surface of Mars",
  "evt-02-20-1998-figure-skating": "At 15, figure skater Tara Lipinski became the then-youngest Winter Olympic champion",
  "evt-02-21-1973-sinai-peninsula": "Israeli fighters shot down Libyan Arab Airlines Flight 114 over Sinai, killing 108",
  "evt-02-21-1919-bavaria": "Kurt Eisner, who had made Bavaria a republic, was assassinated",
  "evt-02-21-2022-prelude-to-the-2022-russian-invasion-of-ukraine": "Putin recognised Donetsk and Luhansk as independent and moved troops into the region",
  "evt-02-23-1778-american-revolutionary-war": "Prussian officer von Steuben arrived at Valley Forge to volunteer for the Continental Army",
  "evt-02-25-1947-nkvd": "The Soviet NKVD abducted Béla Kovács, a turning point in the Communist takeover of Hungary",
  "evt-02-26-1914-hmhs-britannic": "Britannic, the largest sister ship of Titanic, was launched in Belfast",
  "evt-02-28-1914-balkan-wars": "Greeks in southern Albania proclaimed the Autonomous Republic of Northern Epirus",
  "evt-02-29-2020-united-states": "The United States and the Taliban signed the Doha Agreement",
  "evt-03-01-1992-bosnia-and-herzegovina": "Bosnia and Herzegovina declared independence from Yugoslavia",
  "evt-03-01-1921-kronstadt-rebellion": "The Kronstadt rebellion began: sailors took up arms against the Bolsheviks",
  "evt-03-03-1891-shoshone-national-forest": "Shoshone National Forest in Wyoming became the first US national forest",
  "evt-03-07-2007-garuda-indonesia-flight-200": "Garuda Indonesia Flight 200 crashed on landing in Yogyakarta, killing 21 people",
  "evt-03-09-1956-tbilisi": "Soviet soldiers crushed demonstrations in Tbilisi against Khrushchev's de-Stalinization",
  "evt-03-11-1669-mount-etna": "Mount Etna began the eruption that produced its largest lava flow, damaging Catania",
  "evt-03-14-1973-vietnam-war": "John McCain was released after five and a half years as a prisoner in North Vietnam",
  "evt-03-16-1190-york-castle": "Around 150 Jews died at York Castle, most by suicide to escape a mob",
  "evt-03-16-1962-flying-tiger-line-flight-739": "Flying Tiger Line Flight 739 disappeared over the western Pacific with 107 people aboard",
  "evt-03-17-1950-lawrence-berkeley-national-laboratory": "Scientists at Berkeley announced they had made californium, a new element",
  "evt-03-17-2000-uganda": "530 members of a Ugandan cult died in a fire thought to be mass murder or suicide",
  "evt-03-18-1990-isabella-stewart-gardner-museum-theft": "Thieves stole 13 artworks worth $500 million from Boston's Isabella Stewart Gardner Museum",
  "evt-03-19-1979-united-states-house-of-representatives": "The US House of Representatives began televising its daily business on C-SPAN",
  "evt-03-19-1989-egypt": "The Egyptian flag was raised at Taba, ending Israel's occupation that began in 1967",
  "evt-03-20-1923-arts-club-of-chicago": "Picasso's first solo show in the United States opened at the Arts Club of Chicago",
  "evt-03-21-1980-cold-war": "Jimmy Carter announced a US boycott of the Moscow Olympics over the Soviet–Afghan War",
  "evt-03-22-1992-usair-flight-405": "USAir Flight 405 crashed into Flushing Bay shortly after takeoff from LaGuardia",
  "evt-03-22-2024-crocus-city-hall-attack": "At least 145 people were killed in an attack on Crocus City Hall near Moscow",
  "evt-03-26-1991-singapore-airlines-flight-117": "Four Pakistani hijackers diverted Singapore Airlines Flight 117 to Changi Airport",
  "evt-03-27-2016-2016-lahore-suicide-bombing": "A suicide bombing targeting Christians at Easter killed over 70 in a Lahore park",
  "evt-03-27-2015-al-shabaab-militant-group": "Al-Shabab militants seized a Mogadishu hotel, leaving at least 20 people dead",
  "evt-03-28-1997-tragedy-of-otranto": "An Italian Navy ship collided with the Albanian boat Kateri i Radës; dozens died",
  "evt-03-30-2006-cyclone-glenda": "Cyclone Glenda, one of the strongest in the Australian region, hit Western Australia",
  "evt-04-01-1933-wally-hammond": "Wally Hammond scored 336 not out, the highest individual Test cricket score",
  "evt-04-05-2010-upper-big-branch-mine-disaster": "An explosion at the Upper Big Branch Mine in West Virginia killed 29 miners",
  "evt-04-06-1776-american-revolutionary-war": "Continental Navy ships failed to capture HMS Glasgow in the Battle of Block Island",
  "evt-04-06-1945-world-war-ii": "Australian troops won the Battle of Slater's Knoll on Bougainville against Japan",
  "evt-04-07-1926-benito-mussolini": "Benito Mussolini survived an assassination attempt by Irishwoman Violet Gibson",
  "evt-04-08-217-caracalla": "Roman emperor Caracalla was assassinated near Harran and succeeded by Macrinus",
  "evt-04-09-1939-dar-constitution-hall": "Barred from Constitution Hall, Marian Anderson sang on the Lincoln Memorial steps",
  "evt-04-10-2016-puttingal-temple-fire": "Firecrackers exploded at the Paravur temple in Kerala, killing more than 100 people",
  "evt-04-11-2002-2002-venezuelan-coup-attempt": "Venezuelan officers detained President Hugo Chávez in a coup attempt",
  "evt-04-12-2007-2007-iraqi-parliament-bombing": "A suicide bomber struck Iraq's parliament in the Green Zone, killing MP Mohammed Awad",
  "evt-04-13-1777-american-revolutionary-war": "British and Hessian troops surprised a Continental Army outpost at Bound Brook, New Jersey",
  "evt-04-14-2010-2010-yushu-earthquake": "An earthquake in Yushu, China, killed nearly 2,700 people",
  "evt-04-16-1799-french-revolutionary-wars": "Outnumbered French troops repulsed an Ottoman attack at the Battle of Mount Tabor",
  "evt-04-18-2019-united-states-department-of-justice": "The Justice Department released the redacted Mueller report on Russian election meddling",
  "evt-04-20-1968-south-african-airways-flight-228": "South African Airways Flight 228 crashed shortly after takeoff from Windhoek",
  "evt-04-20-1818-court-of-king-s-bench-england": "The accuser in Ashford v Thornton refused trial by battle, and the suspect went free",
  "evt-04-21-1958-united-air-lines-flight-736": "United Airlines Flight 736 collided with an Air Force jet over Nevada, killing all 49",
  "evt-04-23-1993-eritrea": "Eritreans voted overwhelmingly for independence from Ethiopia",
  "evt-04-26-2002-erfurt-school-massacre": "An expelled student killed 16 people at a school in Erfurt, Germany",
  "evt-04-27-2011-2011-super-outbreak": "The 2011 Super Outbreak's worst day: 218 tornadoes killed 317 people in 16 US states",
  "evt-04-28-1986-chernobyl-disaster": "Radiation from Chernobyl was detected in Sweden, forcing the Soviets to admit the accident",
  "evt-04-29-1903-frank-slide": "A rockslide buried part of the Canadian mining town of Frank, killing around 70",
  "evt-04-29-1910-parliament-of-the-united-kingdom": "Britain's Parliament passed the People's Budget to redistribute wealth",
  "evt-04-30-2021-2021-meron-crowd-crush": "A crowd crush at the Mount Meron pilgrimage in Israel killed 45 people",
  "evt-05-01-1897-ramakrishna-mission": "Swami Vivekananda founded the Ramakrishna Mission",
  "evt-05-02-1878-great-mill-disaster": "A dust explosion destroyed Minneapolis's Washburn A Mill, the world's largest flour mill",
  "evt-05-03-1963-birmingham-alabama": "Birmingham police turned fire hoses and dogs on civil rights protesters",
  "evt-05-04-1973-willis-tower": "Chicago's Sears Tower was topped out as the world's tallest building",
  "evt-05-05-1904-pitcher": "Cy Young threw the first perfect game in modern professional baseball",
  "evt-05-07-1992-michigan": "Michigan's ratification made a 203-year-old amendment the 27th Amendment",
  "evt-05-07-1998-mercedes-benz": "Mercedes-Benz bought Chrysler for $40 billion, forming DaimlerChrysler",
  "evt-05-11-1858-minnesota": "Minnesota became the 32nd US state",
  "evt-05-12-1975-mayaguez-incident": "Cambodia's navy seized the American container ship SS Mayaguez",
  "evt-05-14-2008-2008-uefa-cup-final-riots": "Zenit and Rangers fans clashed with police in Manchester's Piccadilly Gardens",
  "evt-05-15-1911-mexican-revolution": "Mexican revolutionaries captured Torreón and massacred 303 Chinese residents",
  "evt-05-16-2003-morocco": "Terrorist attacks in Casablanca killed 33 civilians",
  "evt-05-16-2025-2025-st-louis-tornado": "An EF3 tornado killed five people and caused over $1 billion in damage in St. Louis",
  "evt-05-18-1980-mount-st-helens": "Mount St. Helens erupted, killing about 57 people in Washington state",
  "evt-05-18-2018-cubana-de-aviacion-flight-0972": "Cubana Flight 972 crashed after takeoff from Havana, killing 112 of 113 aboard",
  "evt-05-19-1776-american-revolutionary-war": "A Continental Army garrison near Montreal surrendered at the Battle of the Cedars",
  "evt-05-21-2003-2003-boumerdes-earthquake": "The Boumerdès earthquake in northern Algeria killed more than 2,200 people",
  "evt-05-21-2024-greenfield-tornado": "The Greenfield tornado, with winds estimated above 300 mph, tore across Iowa",
  "evt-05-22-2010-mangaluru": "Air India Express Flight 812 overshot the runway at Mangalore, killing 158",
  "evt-05-22-1766-1766-istanbul-earthquake": "A magnitude 7.1 earthquake and tsunami struck Constantinople",
  "evt-05-22-1826-hms-beagle": "HMS Beagle left Plymouth on her first voyage, to survey Patagonia and Tierra del Fuego",
  "evt-05-24-2014-islamic-extremism": "A gunman killed four people at the Jewish Museum of Belgium in Brussels",
  "evt-05-24-1883-brooklyn-bridge": "The Brooklyn Bridge opened, the longest suspension bridge in the world at the time",
  "evt-05-25-1787-constitutional-convention-united-states": "The Constitutional Convention met in Philadelphia to revise the Articles of Confederation",
  "evt-05-27-1935-supreme-court-of-the-united-states": "The Supreme Court struck down the National Industrial Recovery Act of the New Deal",
  "evt-05-28-1995-1995-neftegorsk-earthquake": "An earthquake destroyed the Russian town of Neftegorsk, killing 1,989 people",
  "evt-05-30-1922-lincoln-memorial": "The Lincoln Memorial opened in Washington",
  "evt-05-30-2012-liberia": "Charles Taylor was sentenced to 50 years for atrocities in Sierra Leone's civil war",
  "evt-06-01-2009-air-france-flight-447": "Air France Flight 447 crashed into the Atlantic, killing all 228 aboard",
  "evt-06-01-2001-nepalese-royal-massacre": "Nepal's Crown Prince Dipendra shot dead his parents and other royals",
  "evt-06-01-2004-oklahoma-city-bombing": "Terry Nichols was sentenced to 161 life terms for the Oklahoma City bombing",
  "evt-06-02-1997-denver": "Timothy McVeigh was convicted of the Oklahoma City bombing, which killed 168 people",
  "evt-06-03-2006-serbia-and-montenegro": "Montenegro declared independence, ending the union with Serbia",
  "evt-06-03-1781-american-revolutionary-war": "Jack Jouett rode 40 miles to warn Thomas Jefferson of British cavalry sent to capture him",
  "evt-06-04-2004-granby-colorado": "Marvin Heemeyer destroyed buildings in Granby, Colorado, with an armored bulldozer",
  "evt-06-07-1965-supreme-court-of-the-united-states": "In Griswold v. Connecticut, the Supreme Court struck down a ban on contraceptives",
  "evt-06-07-1977-silver-jubilee-of-elizabeth-ii": "Half a billion people watched Queen Elizabeth II's Silver Jubilee celebrations on TV",
  "evt-06-08-1941-world-war-ii": "The Allies launched the Syria–Lebanon campaign against Vichy France",
  "evt-06-08-2007-space-shuttle-atlantis": "Space Shuttle Atlantis launched on STS-117 to the International Space Station",
  "evt-06-12-1967-supreme-court-of-the-united-states": "In Loving v. Virginia, the Supreme Court struck down bans on interracial marriage",
  "evt-06-12-2018-united-states": "Donald Trump and Kim Jong-un held the first US–North Korea summit, in Singapore",
  "evt-06-13-1805-lewis-and-clark-expedition": "Meriwether Lewis became the first white American to see the Great Falls of the Missouri",
  "evt-06-14-1940-soviet-ultimatum-to-lithuania": "The Soviet Union ordered Lithuania to admit the Red Army and form a pro-Soviet government",
  "evt-06-15-1992-supreme-court-of-the-united-states": "The Supreme Court ruled the US may forcibly bring suspects from abroad to stand trial",
  "evt-06-15-2006-george-w-bush": "George W. Bush created the Papahānaumokuākea Marine National Monument around Hawaii",
  "evt-06-17-2015-charleston-church-shooting": "A gunman killed nine people at Emanuel AME Church in Charleston, South Carolina",
  "evt-06-18-1972-british-european-airways-flight-548": "BEA Flight 548 crashed near Staines minutes after takeoff from Heathrow, killing all 118",
  "evt-06-19-1838-maryland": "Maryland's Jesuits sold 272 enslaved people to buyers in Louisiana",
  "evt-06-22-2022-june-2022-afghanistan-earthquake": "An earthquake in southeastern Afghanistan killed at least 1,000 people",
  "evt-06-23-1865-stand-watie": "Stand Watie became the last Confederate general to surrender",
  "evt-06-24-2026-2026-venezuela-earthquakes": "Two earthquakes struck Venezuela, killing more than 2,200 people",
  "evt-06-24-1989-1989-tiananmen-square-protests-and-massacre": "After Tiananmen, Jiang Zemin replaced Zhao Ziyang as China's Communist Party leader",
  "evt-06-28-2012-supreme-court-of-the-united-states": "The US Supreme Court upheld the Affordable Care Act's individual mandate",
  "evt-06-30-2013-june-2013-egyptian-protests": "Mass protests began against Egypt's President Morsi, leading to his overthrow",
  "evt-07-03-1863-confederate-states-army": "The Union won the Battle of Gettysburg, a turning point in the American Civil War",
  "evt-07-06-1801-french-revolutionary-wars": "A Royal Navy squadron failed to destroy a French squadron at Algeciras",
  "evt-07-07-1991-yugoslav-wars": "The Brioni Agreement ended the Ten-Day War between Yugoslavia and Slovenia",
  "evt-07-07-1992-new-york-court-of-appeals": "A New York court ruled women have the same right as men to go topless in public",
  "evt-07-08-1947-roswell-incident": "The US military said the \"flying disc\" found near Roswell was a weather balloon",
  "evt-07-09-1640-virginia-governor-s-council": "Virginia made John Punch the first legally recognised slave in England's American colonies",
  "evt-07-10-2017-war-in-iraq-2013-2017": "Iraq declared Mosul fully liberated from the Islamic State",
  "evt-07-13-1863-new-york-city-draft-riots": "Four days of riots began in New York City against the Civil War draft",
  "evt-07-15-1410-crown-of-the-kingdom-of-poland": "Poland and Lithuania defeated the Teutonic Knights at the Battle of Grunwald",
  "evt-07-15-2002-taliban": "\"American Taliban\" John Walker Lindh pleaded guilty to aiding the enemy",
  "evt-07-21-2011-nasa": "Atlantis landed, ending NASA's Space Shuttle program",
  "evt-07-24-1967-montreal": "In Montreal, Charles de Gaulle declared \"Long live free Quebec!\"",
  "evt-07-25-1893-corinth-canal": "The Corinth Canal opened, cutting through the Isthmus of Corinth in Greece",
  "evt-07-26-1977-quebec": "Quebec made French the official language of its provincial government",
  "evt-07-27-1996-atlanta": "A pipe bomb exploded in Atlanta's Centennial Olympic Park during the Olympics",
  "evt-07-29-1014-byzantine-bulgarian-wars": "The Byzantines defeated the Bulgarian Empire at the Battle of Kleidion",
  "evt-07-30-2012-2012-india-blackouts": "A power grid failure left more than 300 million people in northern India without power",
  "evt-07-30-2020-mars-2020": "NASA launched its Mars 2020 mission on an Atlas V rocket",
  "evt-07-31-2012-michael-phelps": "Michael Phelps broke Larisa Latynina's 1964 record for most Olympic medals",
  "evt-08-02-1989-1989-valvettiturai-massacre": "An Indian peacekeeping force massacred 64 Tamil civilians in Sri Lanka",
  "evt-08-03-2014-2014-ludian-earthquake": "An earthquake in Yunnan, China, killed at least 617 people",
  "evt-08-04-2020-2020-beirut-explosion": "An ammonium nitrate explosion at the Port of Beirut killed 218 people",
  "evt-08-05-1716-austro-turkish-war-1716-1718": "The Ottomans failed to take Petrovaradin Fortress despite having twice as many soldiers",
  "evt-08-07-2020-air-india-express-flight-1344": "Air India Express Flight 1344 overshot the runway at Calicut in India",
  "evt-08-07-1946-turkish-straits": "The Soviet Union challenged Turkey's control of the Turkish Straits, escalating the crisis",
  "evt-08-07-2007-oracle-park": "Barry Bonds hit his 756th home run, breaking Hank Aaron's record",
  "evt-08-09-1969-manson-family": "Members of the Manson Family murdered actress Sharon Tate and four guests in Los Angeles",
  "evt-08-09-1988-wayne-gretzky": "Wayne Gretzky was traded from the Edmonton Oilers to the Los Angeles Kings",
  "evt-08-10-1628-vasa-ship": "The Swedish warship Vasa sank on her maiden voyage, just after leaving Stockholm",
  "evt-08-11-1973-dj-kool-herc": "At a New York party, DJ Kool Herc rapped over a break, laying the foundation of hip hop",
  "evt-08-13-2004-democratic-republic-of-the-congo": "156 Congolese Tutsi refugees were massacred at the Gatumba camp in Burundi",
  "evt-08-14-2013-egypt": "Egypt declared a state of emergency as forces killed hundreds of Morsi supporters",
  "evt-08-15-2021-kabul": "Kabul fell to the Taliban as President Ashraf Ghani fled Afghanistan",
  "evt-08-17-1999-1999-izmit-earthquake": "The İzmit earthquake in northwestern Turkey killed more than 17,000 people",
  "evt-08-17-1907-pike-place-market": "Pike Place Market opened in Seattle",
  "evt-08-18-2019-iceland": "Icelanders held a funeral for Okjökull, a glacier that had completely melted",
  "evt-08-19-1999-belgrade": "Tens of thousands rallied in Belgrade to demand Slobodan Milošević's resignation",
  "evt-08-20-1988-yellowstone-fires-of-1988": "Yellowstone's largest wildfire burned more than 150,000 acres in a single day",
  "evt-08-20-1910-washington-state": "Winds merged small fires into the Devil's Broom, the largest fire in recorded US history",
  "evt-08-20-1998-al-shifa-pharmaceutical-factory": "US missiles destroyed Sudan's Al-Shifa factory in retaliation for the embassy bombings",
  "evt-08-22-1991-iceland": "Iceland became the first nation to recognise the independence of the Baltic states",
  "evt-08-25-2017-conflict-in-rakhine-state-2016-present": "Arakan Rohingya Salvation Army attacks in Rakhine State left 170 people dead",
  "evt-08-27-1896-anglo-zanzibar-war": "Zanzibar surrendered to Britain after under an hour — the shortest war in history",
  "evt-08-28-2016-isro": "India's ISRO successfully tested its first scramjet engine",
  "evt-09-01-1985-titanic": "Robert Ballard and Jean-Louis Michel's expedition found the wreck of the Titanic",
  "evt-09-04-1989-leipzig": "The first of Leipzig's weekly Monday demonstrations for democratic reform took place",
  "evt-09-05-2005-mandala-airlines-flight-091": "Mandala Airlines Flight 091 crashed after takeoff in Indonesia, killing 149",
  "evt-09-06-1901-william-mckinley": "President William McKinley was shot by an anarchist in Buffalo and died eight days later",
  "evt-09-07-2004-hurricane-ivan": "Hurricane Ivan struck Grenada, damaging at least 85 percent of its buildings",
  "evt-09-07-2011-lokomotiv-yaroslavl-plane-crash": "A plane carrying the Lokomotiv Yaroslavl hockey team crashed on takeoff near Yaroslavl",
  "evt-09-08-1565-st-augustine-florida": "Spain founded St. Augustine, the oldest continuously occupied European town in the US",
  "evt-09-09-1969-allegheny-airlines-flight-853": "Allegheny Airlines Flight 853 collided with a small plane over Indiana, killing 83",
  "evt-09-10-1779-american-revolutionary-war": "Continental Navy captain William Pickles captured HMS West Florida on Lake Pontchartrain",
  "evt-09-10-2000-operation-barras": "British forces freed hostages held by the West Side Boys militia in Sierra Leone",
  "evt-09-12-1910-gustav-mahler": "Gustav Mahler's Symphony No. 8 premiered in Munich",
  "evt-09-12-1933-leo-szilard": "Waiting at a traffic light in London, Leo Szilard conceived the nuclear chain reaction",
  "evt-09-14-2001-washington-national-cathedral": "A National Prayer Service for the victims of September 11 was held in Washington",
  "evt-09-16-2013-washington-navy-yard-shooting": "A gunman killed twelve people at the Washington Navy Yard",
  "evt-09-21-2013-westgate-shopping-mall-attack": "Gunmen began a three-day attack on Nairobi's Westgate mall that killed 67 people",
  "evt-09-23-1983-gulf-air-flight-771": "Gulf Air Flight 771 from Karachi was bombed by the Abu Nidal Organization, killing all 112",
  "evt-09-23-2004-haiti": "Hurricane Jeanne's floods and mudslides killed over 3,000 people in Haiti",
  "evt-09-23-2008-kauhajoki-school-shooting": "A gunman killed ten students at a college in Kauhajoki, Finland",
  "evt-09-24-2023-nasa": "NASA's OSIRIS-REx capsule landed with samples from the asteroid Bennu",
  "evt-09-25-1775-american-revolutionary-war": "Ethan Allen was captured leading a failed attack on Montreal",
  "evt-09-25-1962-north-yemen-civil-war": "The North Yemen Civil War began when Abdullah al-Sallal overthrew Imam al-Badr",
  "evt-09-26-1907-colony-of-new-zealand": "New Zealand officially became a dominion of the British Empire",
  "evt-09-26-2016-ecnomiohyla-rabborum": "The last known Rabbs' fringe-limbed tree frog died, and the species became extinct",
  "evt-09-27-2019-september-2019-climate-strikes": "Over two million people joined worldwide strikes to protest climate change",
  "evt-10-03-1951-first-battle-of-maryang-san": "The First Battle of Maryang-san began, one of Australia's greatest Korean War feats",
  "evt-10-03-1951-major-league-baseball": "Bobby Thomson hit the \"Shot Heard 'Round the World\" to win the pennant for the Giants",
  "evt-10-03-2015-kunduz-hospital-airstrike": "A US airstrike on a hospital in Kunduz, Afghanistan, killed 42 people",
  "evt-10-05-1966-enrico-fermi-nuclear-generating-station": "A reactor at the Fermi nuclear plant near Detroit suffered a partial meltdown",
  "evt-10-05-2011-mekong-river-massacre": "Two Chinese cargo ships were attacked and their crews murdered on the Mekong River",
  "evt-10-07-1985-1985-puerto-rico-floods": "A landslide in Puerto Rico killed about 130 people, North America's deadliest on record",
  "evt-10-08-1871-great-chicago-fire": "The Great Chicago Fire began, killing 300 people and leaving 90,000 homeless",
  "evt-10-09-1992-peekskill-meteorite": "The Peekskill meteorite crashed into a parked car in Peekskill, New York",
  "evt-10-09-1740-1740-batavia-massacre": "Soldiers began a massacre of Chinese residents in Batavia, killing at least 10,000",
  "evt-10-09-1952-knowsley-hall-shootings": "A footman shot dead two colleagues at Knowsley Hall, England",
  "evt-10-13-1908-suffragette": "Suffragette Margaret Travers Symons became the first woman to speak in the Commons",
  "evt-10-14-2017-al-shabaab-militant-group": "An Al-Shabaab truck bomb in Mogadishu killed 587 people",
  "evt-10-16-1834-palace-of-westminster": "Fire destroyed most of the Palace of Westminster in London",
  "evt-10-17-1777-american-revolutionary-war": "Burgoyne surrendered at Saratoga, ending the British Saratoga campaign",
  "evt-10-17-2017-syrian-civil-war": "The Syrian Democratic Forces took the Islamic State's last foothold in Raqqa",
  "evt-10-18-2019-santiago": "Protests in Santiago escalated, and President Piñera declared a state of emergency",
  "evt-10-18-1989-space-shuttle-atlantis": "Space Shuttle Atlantis launched to deploy the Galileo probe to Jupiter",
  "evt-10-19-1965-vietnam-war": "The Siege of Plei Me began: the first big clash of North Vietnamese and US troops",
  "evt-10-21-1096-first-crusade": "Seljuk forces destroyed the People's Crusade at the Battle of Civetot",
  "evt-10-22-2013-australian-capital-territory": "Australia's Capital Territory became the first jurisdiction to legalise same-sex marriage",
  "evt-10-22-2014-ottawa": "Shootings at Parliament Hill put downtown Ottawa into lockdown",
  "evt-10-23-1972-vietnam-war": "Operation Linebacker, the US bombing of North Vietnam, ended after five months",
  "evt-10-25-2010-mount-merapi": "Mount Merapi in Java began a series of violent eruptions lasting over a month",
  "evt-10-26-1999-united-kingdom": "The House of Lords voted to strip most hereditary peers of their votes",
  "evt-10-27-1942-empire-of-japan": "Japan won a costly victory over the US at the Battle of the Santa Cruz Islands",
  "evt-10-30-1960-royal-infirmary-of-edinburgh": "Michael Woodruff performed the UK's first successful kidney transplant in Edinburgh",
  "evt-10-31-2002-houston": "Former Enron finance chief Andrew Fastow was indicted on 78 counts",
  "evt-11-01-1944-world-war-ii": "A US Superfortress made the first Allied flight over Tokyo since the Doolittle Raid",
  "evt-11-02-2020-vienna": "An ISIL sympathiser killed four people in central Vienna before police shot him",
  "evt-11-03-1992-arkansas": "Bill Clinton defeated George H. W. Bush and Ross Perot to win the US presidency",
  "evt-11-06-1944-b-reactor": "The B Reactor at Hanford began producing plutonium for the Manhattan Project",
  "evt-11-06-1856-scenes-of-clerical-life": "George Eliot submitted her first story, from Scenes of Clerical Life, for publication",
  "evt-11-06-1963-nguyen-ngoc-tho": "Nguyễn Ngọc Thơ was made head of South Vietnam's government after Diệm's assassination",
  "evt-11-08-1966-massachusetts": "Edward Brooke became the first African American popularly elected to the US Senate",
  "evt-11-11-1920-the-cenotaph": "The Cenotaph was unveiled in London and the Unknown Warrior buried in Westminster Abbey",
  "evt-11-12-2001-american-airlines-flight-587": "American Airlines Flight 587 crashed into homes in New York, killing 265 people",
  "evt-11-13-1985-nevado-del-ruiz": "The Nevado del Ruiz eruption sent a mudflow over Armero, Colombia, killing about 23,000",
  "evt-11-13-2000-philippines": "The Philippine House sent articles of impeachment against President Joseph Estrada",
  "evt-11-17-1973-athens-polytechnic-uprising": "Greece's military regime crushed the Athens Polytechnic uprising in bloodshed",
  "evt-11-17-1993-united-states-house-of-representatives": "The US House of Representatives approved the North American Free Trade Agreement",
  "evt-11-18-2014-2014-jerusalem-synagogue-attack": "Two men attacked worshippers at a Jerusalem synagogue; eight people died",
  "evt-11-18-2020-utah-monolith": "Utah wildlife biologists discovered a mysterious metal monolith in the desert",
  "evt-11-19-1985-cold-war": "Ronald Reagan and Mikhail Gorbachev met for the first time, in Geneva",
  "evt-11-21-2022-2022-west-java-earthquake": "An earthquake on the Indonesian island of Java killed at least 335 people",
  "evt-11-24-2016-colombia": "Colombia and FARC signed a revised peace deal ending more than 50 years of war",
  "evt-11-26-2019-2019-albania-earthquake": "An earthquake in western Albania killed at least 52 people",
  "evt-11-27-2009-2009-nevsky-express-bombing": "A bomb derailed a Moscow–Saint Petersburg express train, killing 28 passengers",
  "evt-11-28-1987-south-african-airways-flight-295": "South African Airways Flight 295 caught fire in flight and crashed into the Indian Ocean",
  "evt-11-29-1890-national-diet": "Japan's first parliament, the National Diet, met in Tokyo",
  "evt-11-29-1963-trans-canada-air-lines-flight-831": "Trans-Canada Air Lines Flight 831 crashed after takeoff from Montreal, killing all 118",
  "evt-11-30-2007-atlasjet-flight-4203": "Atlasjet Flight 4203 crashed near Isparta, Turkey, killing 57",
  "evt-12-01-1918-danish-icelandic-act-of-union": "Denmark recognised Iceland as a fully sovereign kingdom in union with the Danish crown",
  "evt-12-03-1999-nasa": "NASA lost contact with the Mars Polar Lander just before it reached Mars",
  "evt-12-05-2017-international-olympic-committee": "The IOC banned Russia from the 2018 Winter Olympics for doping",
  "evt-12-06-2006-nasa": "NASA revealed Mars Global Surveyor images suggesting liquid water on Mars",
  "evt-12-06-1865-slavery-in-the-united-states": "The Thirteenth Amendment was ratified, abolishing slavery in the United States",
  "evt-12-07-1982-texas": "Charles Brooks Jr. became the first person executed by lethal injection in the US",
  "evt-12-07-2011-al-anbar-governorate": "The US handed its last base in Al Anbar to Iraq, ending the Anbar campaign",
  "evt-12-08-1987-arab-israeli-conflict": "An Israeli army vehicle killed four Palestinians at Erez, sparking the First Intifada",
  "evt-12-08-1991-belarus": "Russia, Belarus and Ukraine agreed to dissolve the Soviet Union",
  "evt-12-09-1961-tanganyika-territory": "Tanganyika won independence from Britain",
  "evt-12-10-1941-world-war-ii": "Japanese bombers sank HMS Prince of Wales and HMS Repulse off Malaya",
  "evt-12-14-2008-baghdad": "An Iraqi journalist threw his shoes at George W. Bush in Baghdad",
  "evt-12-16-1811-1811-1812-new-madrid-earthquakes": "The first of the New Madrid earthquakes struck the Midwestern United States",
  "evt-12-17-1926-1926-lithuanian-coup-d-etat": "A military coup in Lithuania replaced President Kazys Grinius with Antanas Smetona",
  "evt-12-19-2016-2016-berlin-truck-attack": "A truck attack on a Berlin Christmas market killed 12 people",
  "evt-12-19-2013-european-space-agency": "ESA launched Gaia to make the most precise catalogue of stars ever",
  "evt-12-21-1995-oslo-ii-accord": "Israeli troops withdrew from Bethlehem under the Oslo II Accord",
  "evt-12-21-2018-special-boat-service": "British special forces stormed a ship in the Thames Estuary to detain four stowaways",
  "evt-12-22-1939-all-india-muslim-league": "The Muslim League celebrated a \"Day of Deliverance\" as Congress ministries resigned",
  "evt-12-23-1990-history-of-slovenia": "Slovenia voted for independence from Yugoslavia in a referendum",
  "evt-12-23-2002-general-atomics-mq-1-predator": "An Iraqi MiG-25 shot down a US Predator — the first air fight between a drone and a jet",
  "evt-12-24-1865-confederate-states-army": "Six Confederate veterans founded the Ku Klux Klan",
  "evt-12-25-2009-northwest-airlines-flight-253": "The \"underwear bomber\" tried to blow up Northwest Airlines Flight 253",
  "evt-12-25-2016-ministry-of-defence-russia": "A military plane carrying the Alexandrov Ensemble crashed into the Black Sea, killing 92",
  "evt-12-26-2003-2003-bam-earthquake": "The Bam earthquake in southeastern Iran killed more than 26,000 people",
  "evt-12-27-1999-burger-king": "Burger King recalled plastic Poké Ball toys as a choking hazard",
  "evt-12-27-1831-hms-beagle": "HMS Beagle left Plymouth with Charles Darwin aboard",
  "evt-12-28-1958-1958-nfl-championship-game": "The Colts beat the Giants in the NFL's first sudden-death overtime — the Greatest Game",
  "evt-12-30-1906-all-india-muslim-league": "The All-India Muslim League was founded in Dhaka",
  "evt-12-31-2011-nasa": "NASA put the first of two GRAIL satellites in orbit around the Moon",
};
